server:
  port: 8888

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5430/human"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
